--Background : Experienced SQL sleuths start here
  --A crime has taken place and the detective needs your help. 
  --The detective gave you the crime scene report, but you somehow lost it. 
  --You vaguely remember that the crime was a ​murder​ that occurred sometime on ​Jan.15, 2018​ and that it took place in ​SQL City​. 
  --Start by retrieving the corresponding crime scene report from the police department’s database.
-- Record your SQL detective process here!  Write down: 
--   1. The SQL queries you ran
--   2. Any notes or insights as SQL comments
--   3. Your final conclusion: who did it?

-- Using these SQL clauses will help you solve the mystery: 
--    SELECT, FROM, WHERE, AND, OR, ORDER BY, LIMIT, LIKE, DISTINCT, BETWEEN, AS
