-- Record your SQL detective process here!  Write down: 
  -- 1. The SQL queries you ran
  -- 2. Any notes or insights as SQL comments
  -- 3. Your final conclusion: who did it?
--Background :
  -- Case #003: The Miami Marina Murder
  --A body was found floating near the docks of Coral Bay Marina in the early hours of August 14, 1986. 
  --Your job, detective, is to find the murderer and bring them to justice.
  --This case might require the use of JOINs, wildcard searches, and logical deduction.
  --Get to work, detective.
