-- Record your SQL detective process here!  Write down: 
  -- 1. The SQL queries you ran
  -- 2. Any notes or insights as SQL comments
  -- 3. Your final conclusion: who did it?
-- Background :
    -- Case #006: The Vanishing Diamond
    -- At Miami’s prestigious Fontainebleau Hotel charity gala, the famous “Heart of Atlantis” diamond necklace suddenly disappeared from its display.
--Tables/schema :
  --crime_scene
  --guest
  --witness_statements
  --attire_registry
  --marina_rentals
  --final_interviews
