-- Record your SQL detective process here!  Write down: 
  -- 1. The SQL queries you ran
  -- 2. Any notes or insights as SQL comments
  -- 3. Your final conclusion: who did it?
--Background :
  -- Case #003: The Miami Marina Murder
  --A body was found floating near the docks of Coral Bay Marina in the early hours of August 14, 1986. 
  --Your job, detective, is to find the murderer and bring them to justice.
  --This case might require the use of JOINs, wildcard searches, and logical deduction.
  --Get to work, detective.
-- Tables/Schema 
  --crime_scene
  --person
  --interviews
  --hotel_checkins
  --surveillance_records
  --confessions
-- Find description of the crime scene using the following query :
--Query 01:
-- SELECT * FROM crime_scene WHERE date=19860814 AND location LIKE 'Coral Bay Marina';
--The above query gives following results:
-- Results
--id	date	location	description
--43	19860814	Coral Bay Marina	The body of an unidentified man was found near the docks. Two people were seen nearby: one who lives on 300ish "Ocean Drive" and another whose first name ends with "ul" and his last name ends with "ez".
-- Find suspects/witnesses???
  -- Query 02:
    -- SELECT * FROM person
    --WHERE ADDRESS LIKE '3%% Ocean Drive%' OR
    --name LIKE '%ul%ez'; 
---The above query gives following results:
--Results
  --id	name	alias	occupation	address
  --5	Michael Santos	Silent Mike	Bartender	33 Ocean Drive
  --101	Carlos Mendez	Los Ojos	Fisherman	369 Ocean Drive
  --102	Raul Gutierrez	The Cobra	Nightclub Owner	45 Sunset Ave
  --105	Victor Martinez	Slick Vic	Bartender	33 Ocean Drive
-- The two people that closely match the description from crime_scene are:
  -- 1. 101 Carlos Mendez who resides at 369 Ocean Drive
  -- 2. 102 Raul Martinez whose first name ends with ul and last name ends with ez
 -- Query 03:
  --SELECT person.name, interviews.transcript FROM
  --person
  --JOIN interviews
  --ON person.id = interviews.person_id
  --WHERE person.address = '369 Ocean Drive' OR
  --person.name = 'Raul Gutierrez'; 
---The above query gives following results: 
--Results
--name	transcript
--Carlos Mendez	I saw someone check into a hotel on August 13. The guy looked nervous.
--Raul Gutierrez	I heard someone checked into a hotel with "Sunset" in the name.
--Correction : These people are probably witnesses who saw a potential suspect that checked into a hotel with "Sunset" in the name on August 13.
 -- Query 04:
  --SELECT person.name, hotel_checkins.hotel_name, hotel_checkins.check_in_date FROM
  --person
  --JOIN hotel_checkins
  --ON person.id = hotel_checkins.person_id
  --WHERE hotel_checkins.hotel_name LIKE '%Sunset%' AND
  --hotel_checkins.check_in_date LIKE '%0813'; 
--The above query gives following results : 
--Results
--name	hotel_name	check_in_date
--Jacob Campbell	Sunset Bay Hotel	19860813
--George Davis	Sunset Harbor Hotel	19860813
--Joseph Taylor	Sunset Palms Resort	19860813
--Christopher Lee	Sunset Shore Hotel	19860813
--Edward Baker	Sunset Marina Inn	19860813
--James Wilson	Sunset Inn	19860813
--Kenneth Green	Sunset Reef Inn	19860813
--Jeffrey Nelson	Sunset Lagoon Resort	19860813
--Robert Smith	Sunset Marina Hotel	19860813
--Nicholas Roberts	Sunset Breeze Hotel	19860813
--Stephen Cooper	Sunset Vista Hotel	19860813
--Donald Cook	Sunset Crest Hotel	19860813
--Charles Peterson	Sunset Palms Hotel	19860813
--Philip Collins	Sunset Beach Inn	19860813
--Gregory Stewart	Sunset Coast Inn	19860813
--Dennis Bailey	Sunset Harbor Inn	19860813
--Douglas Murphy	Sunset Isle Inn	19860813
--Carl Cooper	Sunset Reef Hotel	19860813
--Lawrence Powell	Sunset Lagoon Hotel	19860813
--Sean Fisher	Sunset Grove Inn	19860813
--Wayne Ross	Sunset Dunes Hotel	19860813
--Ralph Coleman	Sunset Shores Inn	19860813
--Randy Perry	Sunset Haven Hotel	19860813
--David Clark	Sunset Beach Hotel	19860813
--Paul Thompson	Sunset Bay Resort	19860813
--Thomas Brown	Sunset Palm Resort	19860813
--Kevin White	Sunset View Inn	19860813
--Richard Moore	Sunset Coast Hotel	19860813
--Daniel Martin	Sunset Sands Inn	19860813
--Steven King	Sunset Beach Resort	19860813
--Brian Hall	Sunset Ocean Hotel	19860813
--Ronald Scott	Sunset Isle Resort	19860813
--Anthony Hill	Sunset Wave Hotel	19860813
--Jason Adams	Sunset Keys Hotel	19860813
--Ryan Phillips	Sunset Point Inn	19860813
--Gary Mitchell	Sunset Grove Resort	19860813
--Eric Carter	Sunset Dunes Inn	19860813
--Andrew Richardson	Sunset Shores Resort	19860813
--Mark Morgan	Sunset Haven Inn	19860813
--Sean Turner	Sunset Oasis Resort	19860813
--Raymond Wood	Sunset Marina Resort	19860813
--Joshua Reed	Sunset Bay Lodge	19860813
--Peter Bell	Sunset View Resort	19860813
--Henry Rivera	Sunset Wave Resort	19860813
--Arthur Bryant	Sunset Keys Inn	19860813
--Terry Butler	Sunset Point Resort	19860813
--Bruce Barnes	Sunset Breeze Resort	19860813
--Eugene Henderson	Sunset Vista Resort	19860813
--John Anderson	Sunset Cove Inn	19860813
--Roy Jenkins	Sunset Crest Resort	19860813

--Next step is to look at the survelliance to see which suspect was acting nervous:
  --Query 05:
    --WITH previous_query AS (SELECT person.id, person.name, hotel_checkins.hotel_name, hotel_checkins.check_in_date FROM
    --person
    --JOIN hotel_checkins
    --ON person.id = hotel_checkins.person_id
    --WHERE hotel_checkins.hotel_name LIKE '%Sunset%' AND
    --hotel_checkins.check_in_date LIKE '%0813'
    --)
    --SELECT surveillance_records.suspicious_activity, previous_query.name
    --FROM previous_query
    --JOIN surveillance_records
    --ON previous_query.id = surveillance_records.person_id 
    --WHERE surveillance_records.suspicious_activity NOT NULL; 
--The above query gives following results:
    -- Results
    -- suspicious_activity	name
    -- Requested newspaper delivery	Jacob Campbell
    -- Asked for directions to beach	Joseph Taylor
    -- Spotted entering late at night	James Wilson
    -- Asked about checkout time	Kenneth Green
    -- Used hotel vending machine	Jeffrey Nelson
    -- Seen arguing with an unknown person	Robert Smith
    -- Used hotel restaurant	Nicholas Roberts
    -- Asked about room service menu	Stephen Cooper
    -- Used ice machine	Gregory Stewart
    -- Requested extra soap	Dennis Bailey
    -- Used hotel phone	Douglas Murphy
    -- Asked about check-in time	Carl Cooper
    -- Used hotel gym	Ralph Coleman
    -- Requested extra pillows	Randy Perry
    -- Requested wake-up call	David Clark
    -- Had breakfast at hotel restaurant	Paul Thompson
    -- Left suddenly at 3 AM	Thomas Brown
    -- Used valet parking	Kevin White
    -- Used the business center	Daniel Martin
    -- Requested city map	Steven King
    -- Used concierge service	Brian Hall
    -- Borrowed pool towels	Anthony Hill
    -- Used the elevator	Andrew Richardson
    -- Requested fresh towels	Mark Morgan
    -- Used hotel parking	Sean Turner
    -- Asked about laundromat service	Raymond Wood
    -- Used lobby restroom	Arthur Bryant
    -- Requested room cleaning	Terry Butler
    -- Used hotel elevator	Bruce Barnes
    -- Asked about breakfast hours	Eugene Henderson
-- Nobody in the above list seems to acting exactly nervous, so next, I will turn to confessions:
  --Query 06:
    --WITH previous_results AS (SELECT confessions.person_id,confessions.confession,person.name FROM confessions 
    --JOIN person
    --ON confessions.person_id = person.id)
    --SELECT previous_results.name, previous_results.confession, surveillance_records.suspicious_activity
    --FROM surveillance_records
    --JOIN previous_results
    --ON previous_results.person_id = surveillance_records.person_id
    --WHERE surveillance_records.suspicious_activity NOT NULL;
--The above query gives following results :
    -- Results
    -- name	confession	suspicious_activity
    -- James Wilson	I don't know anything about this.	Spotted entering late at night
    -- Robert Smith	I was just walking my dog that night.	Seen arguing with an unknown person
    -- Thomas Brown	Alright! I did it. I was paid to make sure he never left the marina alive.	Left suddenly at 3 AM
    -- David Clark	Who are you to question me? I'm an innocent man.	Requested wake-up call
    -- Paul Thompson	I have no idea what you're talking about.	Had breakfast at hotel restaurant
    -- Kevin White	Alright! Fine! I was the one who robbed that bank last month.	Used valet parking
    -- Joseph Taylor	This is ridiculous, I'm innocent!	Asked for directions to beach
    -- Daniel Martin	Alright! I admit it - I've been running an illegal gambling ring.	Used the business center
    -- Steven King	I was nowhere near there that night.	Requested city map
    -- Brian Hall	I don't know what you're investigating.	Used concierge service
    -- Anthony Hill	Alright! I confess to the art gallery heist!	Borrowed pool towels
    -- Kenneth Green	I'm just a simple businessman.	Asked about checkout time
    -- Jeffrey Nelson	Alright! I've been running a smuggling operation.	Used hotel vending machine
    -- Jacob Campbell	This is harassment!	Requested newspaper delivery
    -- Nicholas Roberts	I was at the movies that evening.	Used hotel restaurant
    -- Stephen Cooper	Alright! I've been forging documents.	Asked about room service menu
    -- Andrew Richardson	I'm an honest citizen.	Used the elevator
    -- Mark Morgan	Alright! I confess to the insurance fraud.	Requested fresh towels
    -- Sean Turner	This is all a mistake.	Used hotel parking
    -- Raymond Wood	I was out of town that week.	Asked about laundromat service
    -- Gregory Stewart	You're barking up the wrong tree.	Used ice machine
    -- Dennis Bailey	I'm a law-abiding citizen.	Requested extra soap
    -- Douglas Murphy	Alright! I've been selling stolen electronics.	Used hotel phone
    -- Carl Cooper	Check my records, I'm clean.	Asked about check-in time
    -- Arthur Bryant	Alright! I confess to the warehouse break-in.	Used lobby restroom
    -- Terry Butler	You're making a big mistake.	Requested room cleaning
    -- Bruce Barnes	I was at work all day.	Used hotel elevator
    -- Eugene Henderson	Alright! I confess to hacking the system.	Asked about breakfast hours
    -- Ralph Coleman	I'm being framed!	Used hotel gym
    -- Randy Perry	Alright! I've been selling fake IDs.	Requested extra pillows
    -- Bobby Hughes	Who told you about me?	Used hotel restaurant
    -- Victor Gray	I was asleep at the time.	Asked about local attractions
    -- Walter Long	This is all circumstantial.	Used vending machine
    -- Jesse Brooks	I'm innocent of all charges.	Requested taxi service
    -- Arthur Hayes	Alright! I confess to the corporate espionage.	Used hotel lobby
    -- Lawrence Gordon	I have witnesses for my whereabouts.	Asked about pool hours
    -- Jerry Graham	Alright! I've been selling stolen artwork.	Used hotel VIP parking space
    -- Ray Wallace	You're on a wild goose chase.	Requested room key replacement
    -- Albert Cole	I was with my girlfriend that night.	Used hotel gym
    -- Willie West	This is absurd!	Asked about checkout process
    -- Ralph Fox	I'm a respected member of this community.	Used hotel parking
    -- Bobby Grant	Alright! I confess to the identity theft ring.	Requested wake-up call
    -- Fred Harrison	This is pure speculation.	Used hotel restaurant
    -- Wayne Ellis	I don't know what you mean.	Asked about room service
    -- Earl Stone	Alright! I confess to the tax evasion scheme.	Used business center
    -- Stanley Black	This is all hearsay.	Requested extra towels
    -- Leon Carr	I have nothing to hide.	Used hotel pool
    -- Norman Holmes	Alright! I confess to the insider trading.	Asked about food service
    -- Vernon Rice	I was visiting my mother.	Used valet service
    -- Lewis Shaw	Alright! I've been selling counterfeit goods.	Requested room cleaning
    -- Claude Fleming	You're following a dead end.	Used hotel gym
    -- Cecil Daniels	I have a solid alibi.	Asked about breakfast
    -- Floyd Duncan	Alright! I've been running an illegal import business.	Used hotel restaurant
    -- Lloyd Weber	You're mistaken about me.	Requested extra pillows
    -- Sam Knight	I'm not involved in any way.	Used concierge service
    -- Carlos Mendez	This is just a misunderstanding.	Asked for room service menu
    -- Luis Sanchez	I have proof of my innocence.	Used the spa facilities
    -- Diego Ramirez	You're looking at the wrong person.	Requested late checkout

--Looking at the third row, Thomas Brown seems to be the one to do it as he confesses it
--Thomas Brown	Alright! I did it. I was paid to make sure he never left the marina alive.	Left suddenly at 3 AM
--Thomas Brown is the culprit/murderer.
