-- Record your SQL detective process here!  Write down: 
  -- 1. The SQL queries you ran
  -- 2. Any notes or insights as SQL comments
  -- 3. Your final conclusion: who did it?
-- Background :
-- Case #002: The Stolen Sound
-- In the neon glow of 1980s Los Angeles, the West Hollywood Records store was rocked by a daring theft. 
  --A prized vinyl record, worth over $10,000, vanished during a busy evening, leaving the store owner desperate for answers. 
  --Vaguely recalling the details, you know the incident occurred on July 15, 1983, at this famous store. 
  --Your task is to track down the thief and bring them to justice.
--Tables/Schema
  --crime_scene
  --witnesses
  --suspects
  --interviews
--Queries:
  --Query 01 :
--SELECT * FROM crime_scene WHERE type = 'theft' AND location = 'West Hollywood Records';
-- The above query gives the following result :
--Result
--id	date	type	location	description
--65	19830715	theft	West Hollywood Records	A prized vinyl record was stolen from the store during a busy evening.
  --Query 02:
--SELECT * FROM witnesses WHERE crime_scene_id = 65;
-- The above query gives the following results :
-- Results
-- id	crime_scene_id	clue
-- 28	65	I saw a man wearing a red bandana rushing out of the store.
-- 75	65	The main thing I remember is that he had a distinctive gold watch on his wrist.
-- Notes : This means the man was wearing a red bandana and a distinctive gold watch on his wrist.
  --Query 03:
-- SELECT * FROM suspects WHERE bandana_color = 'red' AND accessory = 'gold watch';
-- The above query gives the following results :
--Results
--id	name	bandana_color	accessory
--35	Tony Ramirez	red	gold watch
--44	Mickey Rivera	red	gold watch
--97	Rico Delgado	red	gold watch

